### ISSUE TITLE
Checklist for remaining AMD Driver fixes

### ISSUE THREAD

**Issue by Xaymar** [Xaymar/OBS-AMD-Advanced-Media-Framework#196]
Title. Patrons can already enjoy it but the bugs still exist anyway.

### Required Fixes:

- [x] OBS 18.0
- [x] https://github.com/GPUOpen-LibrariesAndSDKs/AMF/issues/60 (17.2.1)
- [x] https://github.com/GPUOpen-LibrariesAndSDKs/AMF/issues/62 (17.3.1)
- [x] https://github.com/GPUOpen-LibrariesAndSDKs/AMF/issues/70 (17.3.1)
- [x] https://github.com/GPUOpen-LibrariesAndSDKs/AMF/issues/73 (17.4.1: Workaround found)
- [x] https://github.com/GPUOpen-LibrariesAndSDKs/AMF/issues/80 (17.4.1: Workaround found)

### Optional Fixes:

- [x] https://github.com/GPUOpen-LibrariesAndSDKs/AMF/issues/57 (17.3.1)
- [x] https://github.com/GPUOpen-LibrariesAndSDKs/AMF/issues/58 (17.4.1)
- [x] https://github.com/GPUOpen-LibrariesAndSDKs/AMF/issues/61 (Problem occurs in the Sample tool itself)
- [x] https://github.com/GPUOpen-LibrariesAndSDKs/AMF/issues/63 & https://github.com/GPUOpen-LibrariesAndSDKs/AMF/issues/64
- [x] https://github.com/GPUOpen-LibrariesAndSDKs/AMF/issues/66 (Pre-Pass does nothing on AVC)

**Comment by Benman2785** [comment]
how to be your Patron?

**Comment by Xaymar** [comment]
Simply [click that](http://patreon.com/Xaymar), sign up and subscribe - may require either a credit card or a paypal account.

**Comment by Benman2785** [comment]
thank you ;)

**Comment by Benman2785** [comment]
Pre-pass Mode works great now - better quality for streaming
but havent figured out your settings for twitch-preset (with my own settings my game starts lagging - forced to use basic yet)

**Comment by RaydRaider** [comment]
OBS 18.0 is out, what's next now?

**Comment by Xaymar** [comment]
@RaydRaider AMD

**Comment by MSxDOS** [comment]
17.3.1 are out. Is broken Pre-Pass fixed in those?

**Comment by Xaymar** [comment]
I have not yet heard back from AMD, so unless I do I can't confirm that anything has been fixed yet.

**Comment by Xaymar** [comment]
17.3.1 fixed 3 out of 9 Issues, leaving us with 4 remaining unfixed Issues. Due to current AMD events (Ryzen, Naples) we might not see them fixed until the middle of Q2 2017.

**Comment by Xaymar** [comment]
All required bug fixes are now checked, there will be a public release soon after Patreons get the early access version. Stay tuned!

**Comment by Xaymar** [comment]
Version 1.9.9.10 is now out for Patreons, get it here: https://www.patreon.com/posts/8714209

### Changes relative to 1.9.9.6:
- Added Asynchronous Queue mode (which performs better on CPUs with weaker single core IPC).
- Split OpenCL into OpenCL Transfer and OpenCL Conversion, each of these controlling different things.
- Removed 'Usage' setting as it was useless - we change everything anyway.
- Removed 'Host' and 'OpenGL' "APIs" which aren't actually APIs but merely compatibility options in AMF.
- Fixed 'Filler Data' and 'Enforce HRD' breaking when used with Constant Bitrate.

**Comment by Oldgam3r** [comment]
> All required bug fixes are now checked, there will be a public release soon after Patreons get the early access version. 
> 

How about pre-pass on AVC ? Something move in this area ?

**Comment by Xaymar** [comment]
It's being worked on, but it's optional anyway.

**Comment by Oldgam3r** [comment]
> It's being worked on, but it's optional anyway.

> 
Crap :( , its one of main points for what i was bought rx480 - for streaming . Not your fault , was fals advertising by AMD . They was says about 2-pass but was not says exactly for havc or avc. They was talk about streaming how will be wonderfull with polaris.

**Comment by Xaymar** [comment]
All checklist items have either been worked around or fixed by AMD. Closing.
